export const routed = {
  login: "login",
  userManagement: "user-management",
  productManagement: "product-management",
  eventManagement: "event-management",
  allUser: "user-listing",
  activityLog: "activity-log",
  category: "category",
  subCategory: "sub-category",
  aboutUs: "about-us",
  banner: "banner",
  attribute: "attribute",
  subAttribute: "sub-attribute",
  product: "product",
};
