export const routed = {
  login: "login",
  userManagement: "user-management",
  orderManagement: "order-management",
  productManagement: "product-management",
  eventManagement: "event-management",
  allUser: "user-listing",
  allOrder: "order-listing",
  activityLog: "activity-log",
  category: "category",
  subCategory: "sub-category",
  aboutUs: "about-us",
  banner: "banner",
  attribute: "attribute",
  attributeValue: "attribute-value",
  product: "product",
  productPromotion: "product-promotion",
  create: "create",
  preview: "preview",
};
