export enum OrderStatus {
  PENDING = "PENDING",
  STORE_ACCEPTED = "STORE_ACCEPTED",
  PROCESSING = "PROCESSING",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  RETURN = "RETURN",
  SYSTEM_CANCELED = "SYSTEM_CANCELED",
}

export enum PaymentStatus {
  UNPAID = "UNPAID",
  PAID = "PAID",
}
