export enum UserRoleEnum {
  IT_ADMIN_USER = "IT_ADMIN_USER",
  OPERATION_ADMIN_USER = "OPERATION_ADMIN_USER",
  AUTHORIZER_USER = "AUTHORIZER_USER",
  CHECKER_USER = "CHECKER_USER",
  INPUTTER_USER = "INPUTTER_USER",
  SHOW_ALL = "SHOW_ALL",
  NONE = "NONE",
}
